# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora. 
development:
  #url: http://localhost:8080/solr/
  #url: http://apps.testing.cwrc.ca:8080/solr/solr_core_default
  #url: http://apps.testing.cwrc.ca:8080/solr/solr_core_hydra
  #url: http://apps.testing.cwrc.ca:8983/solr/development
  #url: http://cwrc-apps-07.srv.ualberta.ca:8080/solr/solr_core_hydra
  url: http://localhost:8983/solr/development
test: &TEST
  url: http://127.0.0.1:8983/solr/test
cucumber:
  <<: *TEST
production:
  url: http://localhost:8983/solr/
  # url: http://your.production.server:8080/bl_solr/core0 
